/**
 * 
 */
package org.xbase.com.actions;

public enum MigratorActions {
	COLLECTIONCREATED, COLLECTIONDELETED, COLLECTIONEMBEDDED, DATABASECREATED, VIEWCREATED, 
	DATABASEDELETED, INDEXCREATED, INDEXDELETED, SCHEMACREATED, SCHEMADELETED, VIEWDELETED;
}

